buildscript {
    ext.kotlin_version = '1.7.21'
    ext.dagger_version = '2.45'
    ext.nav_version = '2.5.2'
    ext.moxy_version = '2.2.2'
    ext.paging_version = '2.1.2'
    ext.retrofit_version = '2.9.0'
    ext.room_version = '2.4.3'
    ext.markwon_version = '4.6.2'

    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.2'
        classpath 'com.google.firebase:perf-plugin:1.4.2'
        classpath 'com.google.gms:google-services:4.3.14'
        classpath 'com.hiya:jacoco-android:0.2'
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
    }
}
plugins {
    id "org.sonarqube" version "3.2.0"
}
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}
sonarqube {
    androidVariant 'fullDebug'
    properties {
        property "sonar.java.coveragePlugin", "jacoco"
    }
}