apply plugin: 'com.android.application'

apply plugin: 'androidx.navigation.safeargs'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'kotlin-kapt'

apply plugin: 'com.google.gms.google-services'

apply plugin: 'com.google.firebase.crashlytics'

apply plugin: 'com.google.firebase.firebase-perf'

//apply plugin: 'jacoco-android'
apply plugin: "com.hiya.jacoco-android"

android {
    compileSdkVersion 29
    defaultConfig {
        applicationId "ru.houseofapps.sozidateli"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 53
        versionName "1.0.21"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    dataBinding {
        enabled = true
    }
    lintOptions {
        abortOnError false
        lintConfig file("../lint.xml")
    }

    signingConfigs {
        /*def localFile = rootProject.file("release.properties")
        def propertiesFile = localFile.exists() ? localFile : new File("/home/service/keystore/fond/release.properties")
        if (propertiesFile.exists()) {
            def properties = new Properties()
            properties.load(new FileInputStream(propertiesFile))
            release {
                keyAlias properties.keyAlias
                keyPassword properties.keyAliasPassword
                storePassword properties.keyStorePassword
                storeFile rootProject.file(properties.keyStorePath)
            }
        }*/
        release {
            storeFile file("fond.jks")
            storePassword "fondkeystore"
            keyAlias "fondalias"
            keyPassword "fondaliaskey"
        }
    }

    defaultConfig {
        buildConfigField "String", "DATA_DATA_API_URL", "\"https://suggestions.dadata.ru/\""

        applicationVariants.all { variant ->
            def buildType = variant.buildType.name + "-Frankenstein"
            variant.outputs.all {
                outputFileName = "sozidateli-${buildType}-${variant.versionName}($variant.versionCode).apk"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            if (signingConfigs.hasProperty("release")) signingConfig signingConfigs.release

            buildConfigField "String", "API_URL", "\"https://api.sozidateli.ru/\""
            buildConfigField "String", "NEW_API_URL", "\"https://restapi.sozidateli.ru/\""
            buildConfigField "Boolean", "REGISTER_AGREEMENT_ENABLED", "false"
            buildConfigField "Boolean", "NEW_PROFILE_EDIT", "false"
        }
        beta {
            initWith(debug)
            buildConfigField "String", "API_URL", "\"https://beta-api.sozidateli.ru/\""
            buildConfigField "String", "NEW_API_URL", "\"https://beta-restapi.sozidateli.ru/\""
            buildConfigField "Boolean", "REGISTER_AGREEMENT_ENABLED", "false"
            buildConfigField "Boolean", "NEW_PROFILE_EDIT", "false"
            matchingFallbacks = ['debug', 'release']
        }
        "new" {
            initWith(debug)
            buildConfigField "String", "API_URL", "\"http://alfa-api.sozidateli.ru/\""
            buildConfigField "String", "NEW_API_URL", "\"https://alfa-restapi.sozidateli.ru/\""
            buildConfigField "Boolean", "REGISTER_AGREEMENT_ENABLED", "true"
            buildConfigField "Boolean", "NEW_PROFILE_EDIT", "true"
            matchingFallbacks = ['debug', 'release']
        }
    }

    variantFilter { variant ->
        if (variant.name == "debug") {
            setIgnore(true)
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    testOptions {
        unitTests.includeAndroidResources = true
    }
}

androidExtensions {
    experimental = true
}

repositories {
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(':filepicker')

    // kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    // support
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.2'
    implementation 'androidx.core:core-ktx:1.3.2'

    // google
    implementation platform('com.google.firebase:firebase-bom:25.12.0')
    implementation 'com.google.firebase:firebase-messaging-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-perf-ktx'
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation 'com.google.android.gms:play-services-location:18.0.0'

    // navigation
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"

    // Paging
    implementation "androidx.paging:paging-runtime-ktx:$paging_version"
    implementation "androidx.paging:paging-rxjava2-ktx:$paging_version"

    // rx
    implementation "io.reactivex.rxjava2:rxandroid:2.1.1"
    implementation 'io.reactivex.rxjava2:rxjava:2.2.9'
    implementation 'io.reactivex.rxjava2:rxkotlin:2.3.0'

    // dagger 2
    kapt "com.google.dagger:dagger-compiler:$dagger_version"
    kapt "com.google.dagger:dagger-android-processor:$dagger_version"
    implementation "com.google.dagger:dagger:$dagger_version"
    implementation "com.google.dagger:dagger-android:$dagger_version"
    implementation "com.google.dagger:dagger-android-support:$dagger_version"

    // moxy
    implementation "com.arello-mobile:moxy:$moxy_version"
    implementation "com.arello-mobile:moxy-android:$moxy_version"
    implementation "com.arello-mobile:moxy-app-compat:$moxy_version"
    kapt "com.arello-mobile:moxy-compiler:$moxy_version"

    // Room
    implementation "androidx.room:room-runtime:$room_version"
    kapt "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-rxjava2:$room_version"

    // logs
    implementation 'com.jakewharton.timber:timber:4.7.0'

    //ui
    implementation "com.github.lisawray.groupie:groupie:2.6.0"
    implementation "com.github.lisawray.groupie:groupie-kotlin-android-extensions:2.6.0"
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.budiyev.android:code-scanner:2.1.0'
    implementation 'io.github.inflationx:calligraphy3:3.1.1'
    implementation 'io.github.inflationx:viewpump:2.0.3'
    implementation 'org.sufficientlysecure:html-textview:3.6'
    implementation 'me.saket:better-link-movement-method:2.2.0'
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'
    implementation 'com.wdullaer:materialdatetimepicker:4.1.2'
    implementation 'com.romandanylyk:pageindicatorview:1.0.3'
    implementation 'com.github.shts:StoriesProgressView:3.0.0'
    implementation 'com.facebook.shimmer:shimmer:0.5.0'

    // leakcanary
//    debugImplementation "com.squareup.leakcanary:leakcanary-android:$leakcanary_version"
//    releaseImplementation "com.squareup.leakcanary:leakcanary-android-no-op:$leakcanary_version"

    //utils
    implementation 'org.greenrobot:eventbus:3.1.1'
    implementation 'com.github.FrangSierra:RxFirebase:1.5.6'
    implementation 'com.github.qingmei2:rximagepicker:2.5.1'
    implementation 'com.isseiaoki:simplecropview:1.1.8'
    implementation 'com.github.tbruyelle:rxpermissions:0.10.2'
    implementation 'io.michaelrocks:libphonenumber-android:8.10.16'

    // network
    implementation "com.squareup.retrofit2:retrofit:$retrofit_version"
    implementation "com.squareup.retrofit2:adapter-rxjava2:$retrofit_version"
    implementation "com.squareup.retrofit2:converter-gson:$retrofit_version"
    implementation 'com.squareup.okhttp3:logging-interceptor:4.2.2'
    implementation 'com.github.pwittchen:reactivenetwork-rx2:3.0.3'

    // sn
    implementation 'com.vk:androidsdk:1.6.9'
    implementation 'com.facebook.android:facebook-android-sdk:5.9.0'
    implementation 'ru.ok:odnoklassniki-android-sdk:2.1.8'

    // tests
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    //fragment
    implementation 'androidx.fragment:fragment-ktx:1.3.0-beta01'

    implementation 'com.hbb20:ccp:2.4.5'

    implementation ('io.socket:socket.io-client:1.0.0') {
        exclude group: 'org.json', module: 'json'
    }
}

sonarqube {
    properties {
        property "sonar.jacoco.reportPaths", "build/jacoco/testDebugUnitTest.exec"
        property "sonar.junit.reportsPaths", "build/test-results/*/*.xml"
    }
}
