apply plugin: 'com.android.application'

apply plugin: 'androidx.navigation.safeargs'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'kotlin-kapt'

apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "ru.houseofapps.fond"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            buildConfigField "String", "API_URL", "\"http://api.ha-slsp.ru/\""
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

androidExtensions {
    experimental = true
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(':filepicker')

    // kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    // support
    implementation 'androidx.appcompat:appcompat:1.1.0-alpha02'
    implementation 'com.google.android.material:material:1.1.0-alpha04'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha3'

    // google
    implementation 'com.google.firebase:firebase-core:16.0.7'
    implementation 'com.google.firebase:firebase-firestore:17.1.4'
    implementation 'com.firebaseui:firebase-ui-firestore:4.2.1'
    implementation 'com.google.firebase:firebase-messaging:17.3.4'
    implementation 'com.google.firebase:firebase-auth:16.1.0'
    implementation 'com.google.android.gms:play-services-maps:16.0.0'

    // navigation
    implementation "android.arch.navigation:navigation-fragment-ktx:$nav_version"
    implementation "android.arch.navigation:navigation-ui-ktx:$nav_version"

    // Paging
    implementation "androidx.paging:paging-runtime-ktx:$paging_version"
    implementation "androidx.paging:paging-rxjava2-ktx:$paging_version"

    // rx
    implementation "io.reactivex.rxjava2:rxandroid:2.1.0"
    implementation 'io.reactivex.rxjava2:rxjava:2.2.4'

    // dagger 2
    kapt "com.google.dagger:dagger-compiler:$dagger_version"
    kapt "com.google.dagger:dagger-android-processor:$dagger_version"
    implementation "com.google.dagger:dagger:$dagger_version"
    implementation "com.google.dagger:dagger-android:$dagger_version"
    implementation "com.google.dagger:dagger-android-support:$dagger_version"

    // moxy
    implementation "com.arello-mobile:moxy:$moxy_version"
    implementation "com.arello-mobile:moxy-android:$moxy_version"
    implementation "com.arello-mobile:moxy-app-compat:$moxy_version"
    kapt "com.arello-mobile:moxy-compiler:$moxy_version"

    // logs
    implementation 'com.jakewharton.timber:timber:4.7.0'
    implementation 'com.splunk:mint-android-sdk:5.2.4'


    //ui
    implementation "com.xwray:groupie:2.3.0"
    implementation "com.xwray:groupie-kotlin-android-extensions:2.3.0"
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'
    implementation 'com.budiyev.android:code-scanner:2.1.0'
    implementation 'uk.co.chrisjenx:calligraphy:2.3.0'
    implementation 'org.sufficientlysecure:html-textview:3.6'
    implementation 'me.saket:better-link-movement-method:2.2.0'
    implementation 'com.github.chuross:flinglayout:0.5.0'
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'
    implementation 'com.hbb20:ccp:2.2.4'

    // leakcanary
    debugImplementation "com.squareup.leakcanary:leakcanary-android:$leakcanary_version"
    releaseImplementation "com.squareup.leakcanary:leakcanary-android-no-op:$leakcanary_version"

    //utils
    implementation 'org.greenrobot:eventbus:3.1.1'
    implementation 'com.github.FrangSierra:RxFirebase:1.5.6'
    implementation 'com.github.qingmei2:rximagepicker:2.2.0'
    implementation 'com.isseiaoki:simplecropview:1.1.8'

    // network
    implementation "com.squareup.retrofit2:retrofit:$retrofit_version"
    implementation "com.squareup.retrofit2:adapter-rxjava2:$retrofit_version"
    implementation "com.squareup.retrofit2:converter-gson:$retrofit_version"
    implementation 'com.squareup.okhttp3:logging-interceptor:3.13.0'

    // sn
    implementation 'com.vk:androidsdk:1.6.7'
    implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
    implementation 'ru.ok:odnoklassniki-android-sdk:2.1.6'


    // tests
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
repositories {
    mavenCentral()
}
