apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'androidx.navigation.safeargs'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: "com.hiya.jacoco-android"

android {
    compileSdkVersion 33
    defaultConfig {
        applicationId "ru.houseofapps.sozidateli"
        minSdkVersion 24
        targetSdkVersion 33
        versionCode 67
        versionName "1.0.40"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildFeatures {
        dataBinding = true
        viewBinding = true
    }
    signingConfigs {
        release {
            storeFile file("fond.jks")
            storePassword "fondkeystore"
            keyAlias "fondalias"
            keyPassword "fondaliaskey"
        }
    }

    defaultConfig {
        buildConfigField "String", "DATA_DATA_API_URL", "\"https://suggestions.dadata.ru/\""
        signingConfig signingConfigs.debug

        applicationVariants.configureEach { variant ->
            def buildType = variant.buildType.name + ""
            variant.outputs.configureEach {
                outputFileName = "sozidateli-${buildType}-${variant.versionName}($variant.versionCode).apk"
            }
        }

        def properties = new Properties()
        if (rootProject.file("app/src/new/vk.properties").exists()) {
            properties.load(rootProject.file("app/src/new/vk.properties").newDataInputStream())
        }
        manifestPlaceholders = [
                VKIDRedirectHost  : "vk.com",
                VKIDRedirectScheme: properties.getProperty("client_scheme"),
                VKIDClientID      : properties.getProperty("client_id"),
                VKIDClientSecret  : properties.getProperty("client_secret")
        ]
    }

    buildTypes {
        release {
            minifyEnabled false
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            if (signingConfigs.hasProperty("release")) signingConfig signingConfigs.release

            buildConfigField "String", "SHARE_URL", "\"https://sozidateli.ru/\""
            buildConfigField "String", "SOCKET_URL", "\"https://socket-data-provider.sozidateli.ru/\""

            buildConfigField "String", "API_URL", "\"https://api.sozidateli.ru/\""
            buildConfigField "String", "NEW_API_URL", "\"https://restapi.sozidateli.ru/\""
            buildConfigField "Boolean", "REGISTER_AGREEMENT_ENABLED", "false"
            buildConfigField "Boolean", "NEW_PROFILE_EDIT", "false"
        }
        beta {
            initWith(debug)
            buildConfigField "String", "SHARE_URL", "\"https://beta.sozidateli.ru/\""
            buildConfigField "String", "SOCKET_URL", "\"https://beta-socket-data-provider.sozidateli.ru/\""

            buildConfigField "String", "API_URL", "\"https://beta-api.sozidateli.ru/\""
            buildConfigField "String", "NEW_API_URL", "\"https://beta-restapi.sozidateli.ru/\""
            buildConfigField "Boolean", "REGISTER_AGREEMENT_ENABLED", "false"
            buildConfigField "Boolean", "NEW_PROFILE_EDIT", "false"
            matchingFallbacks = ['debug', 'release']
        }
        "new" {
            initWith(debug)
            buildConfigField "String", "SHARE_URL", "\"https://alfa.sozidateli.ru/\""
            buildConfigField "String", "SOCKET_URL", "\"https://alfa-socket-data-provider.sozidateli.ru/\""

            buildConfigField "String", "API_URL", "\"http://alfa-api.sozidateli.ru/\""
            buildConfigField "String", "NEW_API_URL", "\"https://alfa-restapi.sozidateli.ru/\""
            buildConfigField "Boolean", "REGISTER_AGREEMENT_ENABLED", "true"
            buildConfigField "Boolean", "NEW_PROFILE_EDIT", "true"
            matchingFallbacks = ['debug', 'release']
        }
    }

//    flavorDimensions "version"
//    productFlavors {
//        "new" {
//            dimension "version"
//            buildConfigField "String", "SHARE_URL", "\"https://alfa.sozidateli.ru/\""
//            buildConfigField "String", "SOCKET_URL", "\"https://alfa-socket-data-provider.sozidateli.ru/\""
//
//            buildConfigField "String", "API_URL", "\"http://alfa-api.sozidateli.ru/\""
//            buildConfigField "String", "NEW_API_URL", "\"https://alfa-restapi.sozidateli.ru/\""
//            buildConfigField "Boolean", "REGISTER_AGREEMENT_ENABLED", "true"
//            buildConfigField "Boolean", "NEW_PROFILE_EDIT", "true"
//        }
//    }

    variantFilter { variant ->
        if (variant.name == "debug") {
            setIgnore(true)
        }
    }

    lintOptions {
        abortOnError false
        lintConfig file("../lint.xml")
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    testOptions {
        unitTests.includeAndroidResources = true
    }

    androidExtensions {
        experimental = true
    }
}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':filepicker')
    implementation project(':qrcodegenerator')
    implementation project(':calendarpager')

    //socket
    implementation('io.socket:socket.io-client:1.0.0') {
        exclude group: 'org.json', module: 'json'
    }

    // support
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.fragment:fragment-ktx:1.6.2'
    implementation "androidx.activity:activity-ktx:1.7.2"

    // google
    implementation platform('com.google.firebase:firebase-bom:31.1.1')
    implementation 'com.google.firebase:firebase-messaging-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-perf-ktx'
    implementation 'com.google.android.gms:play-services-maps:18.2.0'
    implementation 'com.google.android.gms:play-services-location:21.0.1'
    implementation 'com.google.maps.android:android-maps-utils:0.4'

    // navigation
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"

    // Paging
    implementation "androidx.paging:paging-runtime-ktx:$paging_version"
    implementation "androidx.paging:paging-rxjava2-ktx:$paging_version"

    // rx
    implementation "io.reactivex.rxjava2:rxandroid:2.1.1"
    implementation 'io.reactivex.rxjava2:rxjava:2.2.19'
    implementation 'io.reactivex.rxjava2:rxkotlin:2.3.0'

    // dagger 2
    implementation "com.google.dagger:dagger:$dagger_version"
    implementation "com.google.dagger:dagger-android:$dagger_version"
    implementation "com.google.dagger:dagger-android-support:$dagger_version"
    kapt "com.google.dagger:dagger-compiler:$dagger_version"
    kapt "com.google.dagger:dagger-android-processor:$dagger_version"

    // moxy
    implementation "com.github.moxy-community:moxy:$moxy_version"
    implementation "com.github.moxy-community:moxy-android:$moxy_version"
    implementation "com.github.moxy-community:moxy-app-compat:$moxy_version"
    kapt "com.github.moxy-community:moxy-compiler:$moxy_version"

    // Room
    implementation "androidx.room:room-runtime:$room_version"
    implementation "androidx.room:room-rxjava2:$room_version"
    kapt "androidx.room:room-compiler:$room_version"

    // logs
    implementation 'com.jakewharton.timber:timber:4.7.1'

    //ui
    implementation 'androidx.core:core-splashscreen:1.0.0-alpha02'
    implementation "com.github.lisawray.groupie:groupie:2.6.0"
    implementation "com.github.lisawray.groupie:groupie-databinding:2.6.0"
    implementation "com.github.lisawray.groupie:groupie-kotlin-android-extensions:2.6.0"
    implementation 'com.squareup.picasso:picasso:2.8'
    implementation 'com.github.bumptech.glide:glide:4.14.2'
    implementation 'com.github.yuriy-budiyev:code-scanner:2.3.2'
    implementation 'io.github.inflationx:calligraphy3:3.1.1'
    implementation 'io.github.inflationx:viewpump:2.0.3'
    implementation 'me.saket:better-link-movement-method:2.2.0'
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'
    implementation 'com.wdullaer:materialdatetimepicker:4.1.2'
    implementation 'com.facebook.shimmer:shimmer:0.5.0'
    implementation 'io.coil-kt:coil:1.1.1'
    implementation 'com.github.Commit451.coil-transformations:transformations:1.0.0'
    implementation "com.airbnb.android:lottie:3.4.0"
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
    implementation 'com.github.Dimezis:BlurView:version-2.0.3'
    //implementation 'io.github.glailton.expandabletextview:expandabletextview:1.0.4'


    //utils
    implementation 'com.github.FrangSierra:RxFirebase:1.5.6'
    implementation 'io.michaelrocks:libphonenumber-android:8.12.31'
    implementation 'com.hbb20:ccp:2.4.5'
    implementation 'com.github.tbruyelle:rxpermissions:0.11'

    //markdown
    implementation "io.noties.markwon:core:$markwon_version"
    implementation "io.noties.markwon:html:$markwon_version"
    implementation "io.noties.markwon:linkify:$markwon_version"
    implementation "io.noties.markwon:inline-parser:$markwon_version"

    // network
    implementation "com.squareup.retrofit2:retrofit:$retrofit_version"
    implementation "com.squareup.retrofit2:adapter-rxjava2:$retrofit_version"
    implementation "com.squareup.retrofit2:converter-gson:$retrofit_version"
    implementation 'com.squareup.okhttp3:logging-interceptor:4.11.0'
    implementation 'com.github.pwittchen:reactivenetwork-rx2:3.0.3'

    // sn
    implementation 'com.vk.id:vkid:1.0.0'

    // tests
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test:rules:1.5.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.4.0'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.2.0'
    androidTestImplementation 'androidx.test.ext:junit-ktx:1.1.5'
    androidTestImplementation 'com.google.firebase:testlab-instr-lib:0.2'

    //Shake bugs
    //implementation 'com.shakebugs:shake:15.3.0'

    // CameraX
    implementation "androidx.camera:camera-camera2:1.0.0-rc01"
    implementation "androidx.camera:camera-lifecycle:1.0.0-rc01"
    implementation 'androidx.camera:camera-view:1.0.0-alpha20'

    //Custom tabs Browser
    implementation 'androidx.browser:browser:1.4.0'
}

sonarqube {
    properties {
        property "sonar.jacoco.reportPaths", "build/jacoco/testDebugUnitTest.exec"
        property "sonar.junit.reportsPaths", "build/test-results/*/*.xml"
    }
}
